### ISSUE TITLE
[DELETED]

### ISSUE THREAD

**Issue by master1ous** [DragonSlayre45432/Azury-Bot-Manager-Leaked#1]
Lmao wut is this

**Comment by DragonSlayre45432** [comment]
It's your bot Manager LOL

**Comment by master1ous** [comment]
An empty repo? LMAO. Either way go ahead and leak my "bot maker". That shit is like 2 years old anyways

**Comment by DragonSlayre45432** [comment]
> An empty repo? LMAO. Either way go ahead and leak my "bot maker". That shit is like 2 years old anyways

alright i got your account token and stuff just to let you know

**Comment by master1ous** [comment]
Bro do you have one of those mental issues where your as dumb as a fucking rock?

**Comment by DragonSlayre45432** [comment]
No, Abuse me (@ac1d) and we will see brothr

**Comment by mrclix1** [comment]
Who are you anyways leak my codes if they are forked or temps

**Comment by master1ous** [comment]
Yeah your not acid, we are literally laughing at you in chat clown 🤣 😂 😆... dipshit

**Comment by DragonSlayre45432** [comment]
> Yeah your not acid, we are literally laughing at you in chat clown 🤣 😂 😆... dipshit

U said somethin about ruining my server?

**Comment by master1ous** [comment]
Let's see, your either the owner of CyberDick, or Milrato.

**Comment by DragonSlayre45432** [comment]
> Let's see, your either the owner of CyberDick, or Milrato.

Nope

**Comment by master1ous** [comment]
Then idk u LOL

**Comment by DragonSlayre45432** [comment]
You know my server is #1 for botshop

**Comment by master1ous** [comment]
SKULL

**Comment by DragonSlayre45432** [comment]
> SKULL

ROVERDEV ON #1

**Comment by master1ous** [comment]
Bro not even I have access to my Azury Studios code, my dev has clown. So stop acting like you got its code 💀

**Comment by master1ous** [comment]
Bro

**Comment by DragonSlayre45432** [comment]
LOL

**Comment by master1ous** [comment]
Alex supports azury dumbass

**Comment by DragonSlayre45432** [comment]
i have ur codes lmfao

**Comment by DragonSlayre45432** [comment]
i could leak rn

**Comment by master1ous** [comment]
LMAO sure you do. If you have it what's the file names?

**Comment by master1ous** [comment]
Whats wrong? You quiet?

**Comment by DragonSlayre45432** [comment]
> Whats wrong? You quiet?

shut

**Comment by DragonSlayre45432** [comment]
files are comin 1 by 1

**Comment by master1ous** [comment]
God I hate dumbasses like you 😒

**Comment by DragonSlayre45432** [comment]
> God I hate dumbasses like you 😒

config.json done and leaked

**Comment by master1ous** [comment]
LMAO

**Comment by master1ous** [comment]
Bro idk if your stupid or smt

**Comment by master1ous** [comment]
But we don't use prefix cmds

**Comment by DragonSlayre45432** [comment]
> But we don't use prefix cmds

all ur bot tokens

**Comment by mrclix1** [comment]
Hey I am from azury u stop trolling or wasting time find someone else to troll and make them ur pray

**Comment by master1ous** [comment]
> > But we don't use prefix cmds
> 
> all ur bot tokens

Sorry u dumb? Those aren't my bot tokens LOL

**Comment by DragonSlayre45432** [comment]
> > > But we don't use prefix cmds
> > 
> > 
> > all ur bot tokens
> 
> Sorry u dumb? Those aren't my bot tokens LOL

noice

**Comment by master1ous** [comment]
Why u trying to frame my dev? LOL

**Comment by master1ous** [comment]
They have worked for me since Azury Studios opened up LMAO

**Comment by DragonSlayre45432** [comment]
> They have worked for me since Azury Studios opened up LMAO

idc

**Comment by master1ous** [comment]
Bro you're embarrassing yourself

**Comment by master1ous** [comment]
Give up you stupid shit

**Comment by DragonSlayre45432** [comment]
> Give up you stupid shit

ello
